-- AlterTable
ALTER TABLE "M003_Store" ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "logo_small" DROP NOT NULL,
ALTER COLUMN "logo_big" DROP NOT NULL,
ALTER COLUMN "footer_faktur" DROP NOT NULL,
ALTER COLUMN "bank_type" DROP NOT NULL;
